# Generated by Django 2.0.6 on 2019-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('hours_taught', models.IntegerField()),
                ('date_of_work', models.DateField()),
                ('date_of_entry', models.DateTimeField()),
            ],
        ),
    ]
